### ISSUE TITLE
`interrupt` test breaks with GHC 9.6 (unix-2.8)

### ISSUE THREAD

**Issue by andreasabel** [takano-akio/filelock#12]
I get this error locally with GHC 9.6.0, but it is also reproduced by the [CI](https://github.com/andreasabel/filelock/actions/runs/4127013276/jobs/7129685854#step:20:29):
```
$ cabal test interrupt --test-show-details=direct
Build profile: -w ghc-9.6.0.20230128 -O1
In order, the following will be built (use -v for more details):
 - filelock-0.1.1.5 (test:interrupt) (configuration changed)
...
Running 1 test suites...
Test suite interrupt: RUNNING...
interrupt: interrupt_test.lock: openFdAt: does not exist (No such file or directory)
Test suite interrupt: FAIL
```
This might be due to changes in the `unix` package from `2.7` to `2.8`, but I don't know...

**Comment by andreasabel** [comment]
Ping @takano-akio : Can you have a look at this?   
`unix-2.8` will soon be standard, with GHC 9.6.

**Comment by andreasabel** [comment]
Ping @takano-akio.
(Note to myself: wrote email to `tak anoak io`).

**Comment by andreasabel** [comment]
I think the problem is caused by an error in migration to `unix-2.8`.  
See my comment at: https://github.com/takano-akio/filelock/pull/9/files#r1133243420

**Comment by ysangkok** [comment]
@andreasabel Would it be possible to revise the bounds of filelock-0.1.1.5 on Hackage, to exclude unix-2.8 and avoid people hitting this problem?

**Comment by andreasabel** [comment]
Done! https://hackage.haskell.org/package/filelock-0.1.1.5/revisions/

**Comment by andreasabel** [comment]
Fixed issue in release https://hackage.haskell.org/package/filelock-0.1.1.6
